@startuml
set namespaceSeparator ::

class "new_project::Auctions::allAuctions.dart::PageMarker" {
  +int index
  {static} +List<PageMarker> values
  {static} +PageMarker ongoing
  {static} +PageMarker finished
  {static} +PageMarker offers
}

"new_project::Auctions::allAuctions.dart::PageMarker" o-- "new_project::Auctions::allAuctions.dart::PageMarker"

class "new_project::Auctions::allAuctions.dart::AllAuctions" {
  +Function navigate
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +UserInfoHandler userHandler
  +_AllAuctionsState createState()
}

"new_project::Auctions::allAuctions.dart::AllAuctions" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::Auctions::allAuctions.dart::AllAuctions" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Auctions::allAuctions.dart::AllAuctions" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"new_project::Auctions::allAuctions.dart::AllAuctions" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Auctions::allAuctions.dart::AllAuctions"

class "new_project::Auctions::allAuctions.dart::_AllAuctionsState" {
  +Function navigate
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +UserInfoHandler userHandler
  -PageMarker _currentPage
  +dynamic referenceTypeDropdownValue
  +dynamic referenceSectorDropdownValue
  +List<List> referenceTypes
  +void initState()
  +Widget build()
  -SliverList _getPageContainer()
  -SliverList _getAuctions()
  -SliverList _getOffers()
  -SliverList _generateBoxes()
  +List getReferenceSectors()
  +List getReferenceTypes()
}

"new_project::Auctions::allAuctions.dart::_AllAuctionsState" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::Auctions::allAuctions.dart::_AllAuctionsState" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Auctions::allAuctions.dart::_AllAuctionsState" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"new_project::Auctions::allAuctions.dart::_AllAuctionsState" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Auctions::allAuctions.dart::_AllAuctionsState" o-- "new_project::Auctions::allAuctions.dart::PageMarker"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Auctions::allAuctions.dart::_AllAuctionsState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin<T>" <|-- "new_project::Auctions::allAuctions.dart::_AllAuctionsState"

class "new_project::Auctions::myauctions.dart::MyAuctions" {
  +Function navigate
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +FilterHandler filterHandler
  +UserInfoHandler userHandler
  +_MyAuctionsState createState()
}

"new_project::Auctions::myauctions.dart::MyAuctions" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Auctions::myauctions.dart::MyAuctions" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"new_project::Auctions::myauctions.dart::MyAuctions" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::Auctions::myauctions.dart::MyAuctions" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Auctions::myauctions.dart::MyAuctions"

class "new_project::Auctions::myauctions.dart::_MyAuctionsState" {
  +Function navigate
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +FilterHandler filterHandler
  +UserInfoHandler userHandler
  +List types
  +dynamic typeDropdownValue
  +TextEditingController title
  +TextEditingController maxParticipants
  +TextEditingController duration
  +List<List> referenceTypes
  +List<List> referenceParameters
  +List<List> rangeReferenceParameters
  +List<List> currentReferenceParameters
  +dynamic referenceSectorDropdownValue
  +dynamic referenceTypeDropdownValue
  +List referenceParameterDropdownValues
  +List<TextEditingController> rangeReferenceParameterControllers
  +List templateIDs
  +Template template
  +dynamic templateIDDropdownValue
  +List<TextEditingController> offerControllers
  +Widget build()
  +Map split()
  +SliverList buildAuctionList()
  +void showTemplateGUI()
  +List getReferenceSectors()
  +List getReferenceTypes()
  +List getReferenceParameters()
}

"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"new_project::Auctions::myauctions.dart::_MyAuctionsState" o-- "new_project::Entities::templateListJSON.dart::Template"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Auctions::myauctions.dart::_MyAuctionsState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin<T>" <|-- "new_project::Auctions::myauctions.dart::_MyAuctionsState"

class "new_project::Entities::auctionDetailsListJSON.dart::AuctionDetailsList" {
  +List<AuctionDetails> auctionDetailsList
  +Map toJson()
}

class "new_project::Entities::auctionDetailsListJSON.dart::AuctionDetails" {
  +int id
  +List<Participant> participants
  +int templateId
  +List<Bid> bids
  +int winningBid
  +Map toJson()
}

class "new_project::Entities::auctionDetailsListJSON.dart::Bid" {
  +int id
  +DateTime time
  +int userId
  +List<KeyValuePair> keyValuePairs
  +Map toJson()
}

class "new_project::Entities::auctionDetailsListJSON.dart::KeyValuePair" {
  +String key
  +dynamic value
  +Map toJson()
}

class "new_project::Entities::auctionDetailsListJSON.dart::Participant" {
  +int userId
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::Filters" {
  +List<ReferenceSector> referenceSectors
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::ReferenceSector" {
  +String name
  +List<ReferenceType> referenceTypes
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::ReferenceType" {
  +String name
  +List<ReferenceParameter> referenceParameters
  +List<RangeReferenceParameter> rangeReferenceParameters
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::RangeReferenceParameter" {
  +String name
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::ReferenceParameter" {
  +String name
  +List<FilterValue> values
  +Map toJson()
}

class "new_project::Entities::filtersJSON.dart::FilterValue" {
  +String filterValue
  +Map toJson()
}

class "new_project::Entities::materialAuctionListJSON.dart::MaterialAuctionList" {
  +List<MaterialAuction> materialAuctions
  +Map toJson()
}

class "new_project::Entities::materialAuctionListJSON.dart::MaterialAuction" {
  +int id
  +String title
  +int ownerId
  +int maxParticipants
  +int currentParticipants
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +MaterialReferenceParameters materialReferenceParameters
  +Map toJson()
}

"new_project::Entities::materialAuctionListJSON.dart::MaterialAuction" o-- "new_project::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"

class "new_project::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters" {
  +String fibersType
  +String resinType
  +int minFiberLength
  +int maxFiberLength
  +String recyclingTechnology
  +String sizing
  +String additives
  +int minVolume
  +int maxVolume
  +int localid
  +Map toJson()
}

class "new_project::Entities::materialOfferListJSON.dart::MaterialOfferList" {
  +List<MaterialOffer> materialOffers
  +Map toJson()
}

class "new_project::Entities::materialOfferListJSON.dart::MaterialOffer" {
  +int id
  +String title
  +int userId
  +int templateId
  +List<KeyValuePair> keyValuePairs
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +MaterialReferenceParameters materialReferenceParameters
  +Map toJson()
}

"new_project::Entities::materialOfferListJSON.dart::MaterialOffer" o-- "new_project::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"

class "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2AuctionList" {
  +List<Referencetype2Auction> referencetype2Auctions
  +Map toJson()
}

class "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction" {
  +int id
  +String title
  +int ownerId
  +int maxParticipants
  +int currentParticipants
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +Referencetype2ReferenceParameters referencetype2ReferenceParameters
  +Map toJson()
}

"new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction" o-- "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters" {
  +String parameter1
  +String parameter2
  +int minVolume
  +int maxVolume
  +int localid
  +Map toJson()
}

class "new_project::Entities::referencetype2OfferListJSON.dart::Referencetype2OfferList" {
  +List<Referencetype2Offer> referencetype2Offers
  +Map toJson()
}

class "new_project::Entities::referencetype2OfferListJSON.dart::Referencetype2Offer" {
  +int id
  +String title
  +int userId
  +int templateId
  +List<KeyValuePair> keyValuePairs
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +Referencetype2ReferenceParameters referencetype2ReferenceParameters
  +Map toJson()
}

"new_project::Entities::referencetype2OfferListJSON.dart::Referencetype2Offer" o-- "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "new_project::Entities::templateListJSON.dart::TemplateList" {
  +List<Template> templates
  +Map toJson()
}

class "new_project::Entities::templateListJSON.dart::Template" {
  +int id
  +List<TemplateString> templateStrings
  +List<TemplateVariable> templateVariables
  +Map toJson()
}

class "new_project::Entities::templateListJSON.dart::TemplateString" {
  +String text
  +Map toJson()
}

class "new_project::Entities::templateListJSON.dart::TemplateVariable" {
  +String key
  +String valueType
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::UserList" {
  +List<User> users
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::User" {
  +int userId
  +String userName
  +String email
  +Password password
  +int age
  +Address address
  +String homePhoneNumber
  +String mobilePhoneNumber
  +String officePhoneNumber
  +String currentType
  +String company
  +List<ParticipatingAuction> participatingAuctions
  +List<Offer> offers
  +List<Inbox> requestInbox
  +List<Inbox> inviteInbox
  +Map toJson()
}

"new_project::Entities::userListJSON.dart::User" o-- "new_project::Entities::userListJSON.dart::Password"
"new_project::Entities::userListJSON.dart::User" o-- "new_project::Entities::userListJSON.dart::Address"

class "new_project::Entities::userListJSON.dart::Address" {
  +String streetAddress
  +String city
  +String state
  +String postalCode
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::Inbox" {
  +DateTime time
  +String status
  +int auctionId
  +int userId
  +int offerId
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::Offer" {
  +int offerId
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::ParticipatingAuction" {
  +int auctionId
  +Map toJson()
}

class "new_project::Entities::userListJSON.dart::Password" {
  +String type
  +String encryption
  +Map toJson()
}

class "new_project::Filters::filtersGUI.dart::FiltersGUI" {
  +FilterHandler filterHandler
  +_FiltersState createState()
}

"new_project::Filters::filtersGUI.dart::FiltersGUI" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Filters::filtersGUI.dart::FiltersGUI"

class "new_project::Filters::filtersGUI.dart::_FiltersState" {
  +FilterHandler filterHandler
  +List<TextEditingController> controllers
  +List<List> referenceTypes
  +List<List> referenceParameters
  +List<List> rangeReferenceParameters
  +List<List> currentReferenceParameters
  +dynamic referenceSectorDropdownValue
  +dynamic referenceTypeDropdownValue
  +List referenceParameterDropdownValues
  +List<TextEditingController> rangeReferenceParameterControllers
  +Widget build()
  +Widget ReturnContent()
  +void showFilterTemplateGUI()
  +List getReferenceSectors()
  +List getReferenceTypes()
  +List getReferenceParameters()
}

"new_project::Filters::filtersGUI.dart::_FiltersState" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Filters::filtersGUI.dart::_FiltersState"

class "new_project::Filters::searchBar.dart::SearchBarGUI" {
  +_SearchBarGUIState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Filters::searchBar.dart::SearchBarGUI"

class "new_project::Filters::searchBar.dart::_SearchBarGUIState" {
  +List<SearchObject> list
  -SearchObject _selectedItem
  -bool _show
  +Widget build()
}

"new_project::Filters::searchBar.dart::_SearchBarGUIState" o-- "new_project::Filters::searchBar.dart::SearchObject"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Filters::searchBar.dart::_SearchBarGUIState"

class "new_project::Filters::searchBar.dart::SearchObject" {
  +dynamic name
  +int id
}

class "new_project::Filters::searchBar.dart::MyTextField" {
  +TextEditingController controller
  +FocusNode focusNode
  +Widget build()
}

"new_project::Filters::searchBar.dart::MyTextField" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"new_project::Filters::searchBar.dart::MyTextField" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "new_project::Filters::searchBar.dart::MyTextField"

class "new_project::Filters::searchBar.dart::PopupListItemWidget" {
  +SearchObject item
  +Widget build()
}

"new_project::Filters::searchBar.dart::PopupListItemWidget" o-- "new_project::Filters::searchBar.dart::SearchObject"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "new_project::Filters::searchBar.dart::PopupListItemWidget"

class "new_project::Handlers::auctionHandler.dart::Auctions" {
  +MaterialAuctionList materialAuctions
  +Referencetype2AuctionList referencetype2Auctions
}

"new_project::Handlers::auctionHandler.dart::Auctions" o-- "new_project::Entities::materialAuctionListJSON.dart::MaterialAuctionList"
"new_project::Handlers::auctionHandler.dart::Auctions" o-- "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2AuctionList"

class "new_project::Handlers::auctionHandler.dart::AuctionHandler" {
  +Function setMainState
  +AuctionDetailsList consumerAuctionDetails
  +AuctionDetailsList supplierAuctionDetails
  +Auctions allAuctions
  +TemplateList consumerContractTemplates
  +TemplateList supplierContractTemplates
  +Auctions myAuctions
  +AuctionDetails currentAuctionDetails
  +UserInfoHandler userHandler
  +int nextAuctionID
  +int nextBidID
  +int nextTemplateID
  +List<Inbox> inbox
  +List inboxAuctionTitles
  +int templateItemCount
  +List<TextEditingController> controllers
  +List valueTypes
  +List dropdownValues
  +List userTypes
  +dynamic dropdownValue
  +void createMaterialAuction()
  +void createReferencetype2Auction()
  +void endAuction()
  +void leaveAuction()
  +void selectAuctionWinner()
  +void viewBid()
  +void setCurrentAuction()
  +List getAuctionTitles()
  +void makeBid()
  +Template getContractTemplate()
  +Container getListTile()
  +void showNotifications()
  +void createContractTemplate()
  +void showContractTemplateGUI()
}

"new_project::Handlers::auctionHandler.dart::AuctionHandler" o-- "new_project::Entities::auctionDetailsListJSON.dart::AuctionDetailsList"
"new_project::Handlers::auctionHandler.dart::AuctionHandler" o-- "new_project::Handlers::auctionHandler.dart::Auctions"
"new_project::Handlers::auctionHandler.dart::AuctionHandler" o-- "new_project::Entities::templateListJSON.dart::TemplateList"
"new_project::Handlers::auctionHandler.dart::AuctionHandler" o-- "new_project::Entities::auctionDetailsListJSON.dart::AuctionDetails"
"new_project::Handlers::auctionHandler.dart::AuctionHandler" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"

class "new_project::Handlers::filterHandler.dart::FilterHandler" {
  +Function setMainState
  +Filters filters
  +MaterialReferenceParameters materialFilter
  +Referencetype2ReferenceParameters referencetype2Filter
  +int localFilteridCounter
  +void updateFilter()
  +void deleteFilter()
  +bool checkFilter()
  +void retrieveFilters()
}

"new_project::Handlers::filterHandler.dart::FilterHandler" o-- "new_project::Entities::filtersJSON.dart::Filters"
"new_project::Handlers::filterHandler.dart::FilterHandler" o-- "new_project::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"
"new_project::Handlers::filterHandler.dart::FilterHandler" o-- "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "new_project::Handlers::offerHandler.dart::Offers" {
  +MaterialOfferList materialOffers
  +Referencetype2OfferList referencetype2Offers
}

"new_project::Handlers::offerHandler.dart::Offers" o-- "new_project::Entities::materialOfferListJSON.dart::MaterialOfferList"
"new_project::Handlers::offerHandler.dart::Offers" o-- "new_project::Entities::referencetype2OfferListJSON.dart::Referencetype2OfferList"

class "new_project::Handlers::offerHandler.dart::OfferHandler" {
  +Function setMainState
  +Offers allOffers
  +Offers myOffers
  +TemplateList consumerOfferTemplates
  +TemplateList supplierOfferTemplates
  +UserInfoHandler userHandler
  +int nextOfferID
  +void createMaterialOffer()
  +void createReferencetype2Offer()
  +void endOffer()
  +void viewOffer()
}

"new_project::Handlers::offerHandler.dart::OfferHandler" o-- "new_project::Handlers::offerHandler.dart::Offers"
"new_project::Handlers::offerHandler.dart::OfferHandler" o-- "new_project::Entities::templateListJSON.dart::TemplateList"
"new_project::Handlers::offerHandler.dart::OfferHandler" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"

class "new_project::Handlers::userInfoHandler.dart::UserInfoHandler" {
  +Function updateUser
  +UserList userListObject
  +User user
  +bool isEmail()
  +bool userCheck()
  +String passHasher()
  +bool passwordChecker()
  +bool phoneCheck()
  +bool profileEditCheck()
  +bool passwordValidator()
  +User loginValidator()
  +void login()
  +void register()
  +void updateProfile()
  +void requestToJoin()
  +void inviteToAuction()
}

"new_project::Handlers::userInfoHandler.dart::UserInfoHandler" o-- "new_project::Entities::userListJSON.dart::UserList"
"new_project::Handlers::userInfoHandler.dart::UserInfoHandler" o-- "new_project::Entities::userListJSON.dart::User"

class "new_project::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "new_project::main.dart::MyApp"

class "new_project::mainGUI.dart::WidgetMarker" {
  +int index
  {static} +List<WidgetMarker> values
  {static} +WidgetMarker auctions
  {static} +WidgetMarker login
  {static} +WidgetMarker register
  {static} +WidgetMarker profile
  {static} +WidgetMarker forgotPass
  {static} +WidgetMarker room
}

"new_project::mainGUI.dart::WidgetMarker" o-- "new_project::mainGUI.dart::WidgetMarker"

class "new_project::mainGUI.dart::MainGUI" {
  +State createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::mainGUI.dart::MainGUI"

class "new_project::mainGUI.dart::MainGUIState" {
  +WidgetMarker selectedWidgetMarker
  +AnimationController controller
  +Animation animation
  +UserInfoHandler userHandler
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +int nextAuctionID
  +int nextBidID
  +int nextTemplateID
  +int nextOfferID
  +void initState()
  +void dispose()
  +Widget build()
  +dynamic playAnimation()
  +void setMainState()
  +void updateUser()
  +void navigate()
  +Widget getCustomContainer()
  +Widget getAuctionsGUIContainer()
  +Widget getLoginContainer()
  +Widget getRegisterContainer()
  +Widget getForgotPassContainer()
  +Widget getProfileContainer()
  +Widget getRoomContainer()
}

"new_project::mainGUI.dart::MainGUIState" o-- "new_project::mainGUI.dart::WidgetMarker"
"new_project::mainGUI.dart::MainGUIState" o-- "flutter::src::animation::animation_controller.dart::AnimationController"
"new_project::mainGUI.dart::MainGUIState" o-- "flutter::src::animation::animation.dart::Animation"
"new_project::mainGUI.dart::MainGUIState" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::mainGUI.dart::MainGUIState" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::mainGUI.dart::MainGUIState" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::mainGUI.dart::MainGUIState" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::mainGUI.dart::MainGUIState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin<T>" <|-- "new_project::mainGUI.dart::MainGUIState"

class "new_project::Navigation::navbar.dart::NavigationBar" {
  +Function navigate
  +Function showContractTemplateGUI
  +Function showNotifications
  +UserInfoHandler userHandler
  +int counter
  +Size preferredSize
  +NavigationState createState()
}

"new_project::Navigation::navbar.dart::NavigationBar" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Navigation::navbar.dart::NavigationBar" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Navigation::navbar.dart::NavigationBar"
"flutter::src::widgets::preferred_size.dart::PreferredSizeWidget" <|-- "new_project::Navigation::navbar.dart::NavigationBar"

class "new_project::Navigation::navbar.dart::NavigationState" {
  +Function navigate
  +Function showContractTemplateGUI
  +Function showNotifications
  +UserInfoHandler userHandler
  +int counter
  +Widget build()
  +Widget getNotificationsWidgetCounter()
}

"new_project::Navigation::navbar.dart::NavigationState" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Navigation::navbar.dart::NavigationState"

class "new_project::Navigation::nav_item.dart::NavigationItem" {
  +dynamic title
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "new_project::Navigation::nav_item.dart::NavigationItem"

class "new_project::Pages::auctionsGUI.dart::AuctionsGUI" {
  +Function navigate
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +UserInfoHandler userHandler
  +Widget build()
}

"new_project::Pages::auctionsGUI.dart::AuctionsGUI" o-- "new_project::Handlers::filterHandler.dart::FilterHandler"
"new_project::Pages::auctionsGUI.dart::AuctionsGUI" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Pages::auctionsGUI.dart::AuctionsGUI" o-- "new_project::Handlers::offerHandler.dart::OfferHandler"
"new_project::Pages::auctionsGUI.dart::AuctionsGUI" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "new_project::Pages::auctionsGUI.dart::AuctionsGUI"

class "new_project::Pages::forgotPass.dart::ForgotPasswordScreen" {
  +Function navigate
  +ForgotPasswordState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Pages::forgotPass.dart::ForgotPasswordScreen"

class "new_project::Pages::forgotPass.dart::ForgotPasswordState" {
  +Function navigate
  +Widget build()
  +dynamic launchMailto()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Pages::forgotPass.dart::ForgotPasswordState"

class "new_project::Pages::login.dart::LoginScreen" {
  +Function navigate
  +UserInfoHandler userHandler
  +Login createState()
}

"new_project::Pages::login.dart::LoginScreen" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Pages::login.dart::LoginScreen"

class "new_project::Pages::login.dart::Login" {
  +Function navigate
  +UserInfoHandler userHandler
  -TextEditingController _controllerUserName
  -TextEditingController _controllerPW
  +dynamic loginUserName
  +dynamic loginPW
  +Widget build()
}

"new_project::Pages::login.dart::Login" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Pages::login.dart::Login" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Pages::login.dart::Login"

class "new_project::Pages::profile.dart::ProfileGUI" {
  +Function navigate
  +UserInfoHandler userHandler
  +Profile createState()
}

"new_project::Pages::profile.dart::ProfileGUI" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Pages::profile.dart::ProfileGUI"

class "new_project::Pages::profile.dart::Profile" {
  +Function navigate
  +UserInfoHandler userHandler
  -GlobalKey<FormState> _formKey
  -TextEditingController _controllerUserName
  -TextEditingController _controllerEmail
  -TextEditingController _controllerAge
  -TextEditingController _controllerAddress
  -TextEditingController _controllerCity
  -TextEditingController _controllerState
  -TextEditingController _controllerPostalCode
  -TextEditingController _controllerHomePhoneNumber
  -TextEditingController _controllerMobilePhoneNumber
  -TextEditingController _controllerOfficePhoneNumber
  -TextEditingController _controllerCompany
  -TextEditingController _controllerOPW
  -TextEditingController _controllerPW
  -TextEditingController _controllerRPW
  +dynamic newUserName
  +dynamic newEmail
  +int newAge
  +dynamic newAddress
  +dynamic newCity
  +dynamic newState
  +dynamic newPostalCode
  +dynamic newHomePhoneNumber
  +dynamic newMobilePhoneNumber
  +dynamic newOfficePhoneNumber
  +dynamic newCurrentType
  +dynamic newCompany
  +dynamic opw
  +dynamic pw
  +dynamic rpw
  +Widget build()
}

"new_project::Pages::profile.dart::Profile" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Pages::profile.dart::Profile" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"new_project::Pages::profile.dart::Profile" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Pages::profile.dart::Profile"

class "new_project::Pages::register.dart::RegisterScreen" {
  +Function navigate
  +UserInfoHandler userHandler
  +Register createState()
}

"new_project::Pages::register.dart::RegisterScreen" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Pages::register.dart::RegisterScreen"

class "new_project::Pages::register.dart::Register" {
  +Function navigate
  +UserInfoHandler userHandler
  -TextEditingController _controllerUserName
  -TextEditingController _controllerEmail
  -TextEditingController _controllerPW
  -TextEditingController _controllerRPW
  +dynamic newUserName
  +dynamic newEmail
  +dynamic pw
  +dynamic rpw
  +Widget build()
}

"new_project::Pages::register.dart::Register" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Pages::register.dart::Register" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Pages::register.dart::Register"

class "new_project::Pages::room.dart::Room" {
  +Function navigate
  +AuctionHandler auctionHandler
  -UserInfoHandler _userHandler
  +_RoomState createState()
}

"new_project::Pages::room.dart::Room" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Pages::room.dart::Room" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "new_project::Pages::room.dart::Room"

class "new_project::Pages::room.dart::_RoomState" {
  +Function navigate
  +AuctionHandler auctionHandler
  +UserInfoHandler userHandler
  +CountdownTimerController controller
  +List<Inbox> out
  +Template contractTemplate
  +List<TextEditingController> controllers
  +MaterialAuction materialAuction
  +Referencetype2Auction referencetype2Auction
  +bool isFinished
  +bool isHost
  +TextStyle smallText
  +TextStyle bigText
  +TextStyle boldText
  +Widget build()
  +bool checkForNotifications()
  +void showContractGUI()
}

"new_project::Pages::room.dart::_RoomState" o-- "new_project::Handlers::auctionHandler.dart::AuctionHandler"
"new_project::Pages::room.dart::_RoomState" o-- "new_project::Handlers::userInfoHandler.dart::UserInfoHandler"
"new_project::Pages::room.dart::_RoomState" o-- "flutter_countdown_timer::countdown_timer_controller.dart::CountdownTimerController"
"new_project::Pages::room.dart::_RoomState" o-- "new_project::Entities::templateListJSON.dart::Template"
"new_project::Pages::room.dart::_RoomState" o-- "new_project::Entities::materialAuctionListJSON.dart::MaterialAuction"
"new_project::Pages::room.dart::_RoomState" o-- "new_project::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction"
"new_project::Pages::room.dart::_RoomState" o-- "flutter::src::painting::text_style.dart::TextStyle"
"flutter::src::widgets::framework.dart::State<T>" <|-- "new_project::Pages::room.dart::_RoomState"


@enduml