@startuml
set namespaceSeparator ::



class "Auctioneer::Auctions::allAuctions.dart::_AllAuctionsState" {
  +Function navigate
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +UserInfoHandler userHandler
  -PageMarker _currentPage
  +dynamic referenceTypeDropdownValue
  +dynamic referenceSectorDropdownValue
  +List<List> referenceTypes
  +void initState()
  +Widget build()
  -SliverList _getPageContainer()
  -SliverList _getAuctions()
  -SliverList _getOffers()
  -SliverList _generateBoxes()
  +List getReferenceSectors()
  +List getReferenceTypes()
}

"Auctioneer::Auctions::allAuctions.dart::_AllAuctionsState" o-- "Auctioneer::Handlers::filterHandler.dart::FilterHandler"
"Auctioneer::Auctions::allAuctions.dart::_AllAuctionsState" o-- "Auctioneer::Handlers::auctionHandler.dart::AuctionHandler"
"Auctioneer::Auctions::allAuctions.dart::_AllAuctionsState" o-- "Auctioneer::Handlers::offerHandler.dart::OfferHandler"
"Auctioneer::Auctions::allAuctions.dart::_AllAuctionsState" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"


class "Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" {
  +Function navigate
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +FilterHandler filterHandler
  +UserInfoHandler userHandler
  +List types
  +dynamic typeDropdownValue
  +TextEditingController title
  +TextEditingController maxParticipants
  +TextEditingController duration
  +List<List> referenceTypes
  +List<List> referenceParameters
  +List<List> rangeReferenceParameters
  +List<List> currentReferenceParameters
  +dynamic referenceSectorDropdownValue
  +dynamic referenceTypeDropdownValue
  +List referenceParameterDropdownValues
  +List<TextEditingController> rangeReferenceParameterControllers
  +List templateIDs
  +Template template
  +dynamic templateIDDropdownValue
  +List<TextEditingController> offerControllers
  +Widget build()
  +Map split()
  +SliverList buildAuctionList()
  +void showTemplateGUI()
  +List getReferenceSectors()
  +List getReferenceTypes()
  +List getReferenceParameters()
}

"Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" o-- "Auctioneer::Handlers::auctionHandler.dart::AuctionHandler"
"Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" o-- "Auctioneer::Handlers::offerHandler.dart::OfferHandler"
"Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" o-- "Auctioneer::Handlers::filterHandler.dart::FilterHandler"
"Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"
"Auctioneer::Auctions::myauctions.dart::_MyAuctionsState" o-- "Auctioneer::Entities::templateListJSON.dart::Template"

class "Auctioneer::Entities::auctionDetailsListJSON.dart::AuctionDetailsList" {
  +List<AuctionDetails> auctionDetailsList
  +Map toJson()
}

class "Auctioneer::Entities::auctionDetailsListJSON.dart::AuctionDetails" {
  +int id
  +List<Participant> participants
  +int templateId
  +List<Bid> bids
  +int winningBid
  +Map toJson()
}

class "Auctioneer::Entities::filtersJSON.dart::Filters" {
  +List<ReferenceSector> referenceSectors
  +Map toJson()
}

class "Auctioneer::Entities::filtersJSON.dart::ReferenceSector" {
  +String name
  +List<ReferenceType> referenceTypes
  +Map toJson()
}

class "Auctioneer::Entities::filtersJSON.dart::ReferenceType" {
  +String name
  +List<ReferenceParameter> referenceParameters
  +List<RangeReferenceParameter> rangeReferenceParameters
  +Map toJson()
}

class "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialAuctionList" {
  +List<MaterialAuction> materialAuctions
  +Map toJson()
}

class "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialAuction" {
  +int id
  +String title
  +int ownerId
  +int maxParticipants
  +int currentParticipants
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +MaterialReferenceParameters materialReferenceParameters
  +Map toJson()
}

"Auctioneer::Entities::materialAuctionListJSON.dart::MaterialAuction" o-- "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"

class "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters" {
  +String fibersType
  +String resinType
  +int minFiberLength
  +int maxFiberLength
  +String recyclingTechnology
  +String sizing
  +String additives
  +int minVolume
  +int maxVolume
  +int localid
  +Map toJson()
}

class "Auctioneer::Entities::materialOfferListJSON.dart::MaterialOfferList" {
  +List<MaterialOffer> materialOffers
  +Map toJson()
}

class "Auctioneer::Entities::materialOfferListJSON.dart::MaterialOffer" {
  +int id
  +String title
  +int userId
  +int templateId
  +List<KeyValuePair> keyValuePairs
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +MaterialReferenceParameters materialReferenceParameters
  +Map toJson()
}

"Auctioneer::Entities::materialOfferListJSON.dart::MaterialOffer" o-- "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"

class "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2AuctionList" {
  +List<Referencetype2Auction> referencetype2Auctions
  +Map toJson()
}

class "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction" {
  +int id
  +String title
  +int ownerId
  +int maxParticipants
  +int currentParticipants
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +Referencetype2ReferenceParameters referencetype2ReferenceParameters
  +Map toJson()
}

"Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction" o-- "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters" {
  +String parameter1
  +String parameter2
  +int minVolume
  +int maxVolume
  +int localid
  +Map toJson()
}

class "Auctioneer::Entities::referencetype2OfferListJSON.dart::Referencetype2OfferList" {
  +List<Referencetype2Offer> referencetype2Offers
  +Map toJson()
}

class "Auctioneer::Entities::referencetype2OfferListJSON.dart::Referencetype2Offer" {
  +int id
  +String title
  +int userId
  +int templateId
  +List<KeyValuePair> keyValuePairs
  +DateTime startDate
  +DateTime stopDate
  +String referenceSector
  +String referenceType
  +Referencetype2ReferenceParameters referencetype2ReferenceParameters
  +Map toJson()
}

"Auctioneer::Entities::referencetype2OfferListJSON.dart::Referencetype2Offer" o-- "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "Auctioneer::Entities::templateListJSON.dart::TemplateList" {
  +List<Template> templates
  +Map toJson()
}

class "Auctioneer::Entities::templateListJSON.dart::Template" {
  +int id
  +List<TemplateString> templateStrings
  +List<TemplateVariable> templateVariables
  +Map toJson()
}


class "Auctioneer::Entities::userListJSON.dart::User" {
  +int userId
  +String userName
  +String email
  +Password password
  +int age
  +Address address
  +String homePhoneNumber
  +String mobilePhoneNumber
  +String officePhoneNumber
  +String currentType
  +String company
  +List<ParticipatingAuction> participatingAuctions
  +List<Offer> offers
  +List<Inbox> requestInbox
  +List<Inbox> inviteInbox
  +Map toJson()
}


class "Auctioneer::Filters::filtersGUI.dart::_FiltersState" {
  +FilterHandler filterHandler
  +List<TextEditingController> controllers
  +List<List> referenceTypes
  +List<List> referenceParameters
  +List<List> rangeReferenceParameters
  +List<List> currentReferenceParameters
  +dynamic referenceSectorDropdownValue
  +dynamic referenceTypeDropdownValue
  +List referenceParameterDropdownValues
  +List<TextEditingController> rangeReferenceParameterControllers
  +Widget build()
  +Widget ReturnContent()
  +void showFilterTemplateGUI()
  +List getReferenceSectors()
  +List getReferenceTypes()
  +List getReferenceParameters()
}

"Auctioneer::Filters::filtersGUI.dart::_FiltersState" o-- "Auctioneer::Handlers::filterHandler.dart::FilterHandler"


class "Auctioneer::Handlers::auctionHandler.dart::Auctions" {
  +MaterialAuctionList materialAuctions
  +Referencetype2AuctionList referencetype2Auctions
}

"Auctioneer::Handlers::auctionHandler.dart::Auctions" o-- "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialAuctionList"
"Auctioneer::Handlers::auctionHandler.dart::Auctions" o-- "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2AuctionList"

class "Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" {
  +Function setMainState
  +AuctionDetailsList consumerAuctionDetails
  +AuctionDetailsList supplierAuctionDetails
  +Auctions allAuctions
  +TemplateList consumerContractTemplates
  +TemplateList supplierContractTemplates
  +Auctions myAuctions
  +AuctionDetails currentAuctionDetails
  +UserInfoHandler userHandler
  +int nextAuctionID
  +int nextBidID
  +int nextTemplateID
  +List<Inbox> inbox
  +List inboxAuctionTitles
  +int templateItemCount
  +List<TextEditingController> controllers
  +List valueTypes
  +List dropdownValues
  +List userTypes
  +dynamic dropdownValue
  +void createMaterialAuction()
  +void createReferencetype2Auction()
  +void endAuction()
  +void leaveAuction()
  +void selectAuctionWinner()
  +void viewBid()
  +void setCurrentAuction()
  +List getAuctionTitles()
  +void makeBid()
  +Template getContractTemplate()
  +Container getListTile()
  +void showNotifications()
  +void createContractTemplate()
  +void showContractTemplateGUI()
}

"Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" o-- "Auctioneer::Entities::auctionDetailsListJSON.dart::AuctionDetailsList"
"Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" o-- "Auctioneer::Handlers::auctionHandler.dart::Auctions"
"Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" o-- "Auctioneer::Entities::templateListJSON.dart::TemplateList"
"Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" o-- "Auctioneer::Entities::auctionDetailsListJSON.dart::AuctionDetails"
"Auctioneer::Handlers::auctionHandler.dart::AuctionHandler" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"

class "Auctioneer::Handlers::filterHandler.dart::FilterHandler" {
  +Function setMainState
  +Filters filters
  +MaterialReferenceParameters materialFilter
  +Referencetype2ReferenceParameters referencetype2Filter
  +int localFilteridCounter
  +void updateFilter()
  +void deleteFilter()
  +bool checkFilter()
  +void retrieveFilters()
}

"Auctioneer::Handlers::filterHandler.dart::FilterHandler" o-- "Auctioneer::Entities::filtersJSON.dart::Filters"
"Auctioneer::Handlers::filterHandler.dart::FilterHandler" o-- "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialReferenceParameters"
"Auctioneer::Handlers::filterHandler.dart::FilterHandler" o-- "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2ReferenceParameters"

class "Auctioneer::Handlers::offerHandler.dart::Offers" {
  +MaterialOfferList materialOffers
  +Referencetype2OfferList referencetype2Offers
}

"Auctioneer::Handlers::offerHandler.dart::Offers" o-- "Auctioneer::Entities::materialOfferListJSON.dart::MaterialOfferList"
"Auctioneer::Handlers::offerHandler.dart::Offers" o-- "Auctioneer::Entities::referencetype2OfferListJSON.dart::Referencetype2OfferList"

class "Auctioneer::Handlers::offerHandler.dart::OfferHandler" {
  +Function setMainState
  +Offers allOffers
  +Offers myOffers
  +TemplateList consumerOfferTemplates
  +TemplateList supplierOfferTemplates
  +UserInfoHandler userHandler
  +int nextOfferID
  +void createMaterialOffer()
  +void createReferencetype2Offer()
  +void endOffer()
  +void viewOffer()
}

"Auctioneer::Handlers::offerHandler.dart::OfferHandler" o-- "Auctioneer::Handlers::offerHandler.dart::Offers"
"Auctioneer::Handlers::offerHandler.dart::OfferHandler" o-- "Auctioneer::Entities::templateListJSON.dart::TemplateList"
"Auctioneer::Handlers::offerHandler.dart::OfferHandler" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"

class "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler" {
  +Function updateUser
  +UserList userListObject
  +User user
  +bool isEmail()
  +bool userCheck()
  +String passHasher()
  +bool passwordChecker()
  +bool phoneCheck()
  +bool profileEditCheck()
  +bool passwordValidator()
  +User loginValidator()
  +void login()
  +void register()
  +void updateProfile()
  +void requestToJoin()
  +void inviteToAuction()
}

"Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler" o-- "Auctioneer::Entities::userListJSON.dart::User"


class "Auctioneer::mainGUI.dart::WidgetMarker" {
  +int index
  {static} +List<WidgetMarker> values
  {static} +WidgetMarker auctions
  {static} +WidgetMarker login
  {static} +WidgetMarker register
  {static} +WidgetMarker profile
  {static} +WidgetMarker forgotPass
  {static} +WidgetMarker room
}

"Auctioneer::mainGUI.dart::WidgetMarker" o-- "Auctioneer::mainGUI.dart::WidgetMarker"


class "Auctioneer::mainGUI.dart::MainGUIState" {
  +WidgetMarker selectedWidgetMarker
  +AnimationController controller
  +Animation animation
  +UserInfoHandler userHandler
  +FilterHandler filterHandler
  +AuctionHandler auctionHandler
  +OfferHandler offerHandler
  +int nextAuctionID
  +int nextBidID
  +int nextTemplateID
  +int nextOfferID
  +void initState()
  +void dispose()
  +Widget build()
  +dynamic playAnimation()
  +void setMainState()
  +void updateUser()
  +void navigate()
  +Widget getCustomContainer()
  +Widget getAuctionsGUIContainer()
  +Widget getLoginContainer()
  +Widget getRegisterContainer()
  +Widget getForgotPassContainer()
  +Widget getProfileContainer()
  +Widget getRoomContainer()
}

"Auctioneer::mainGUI.dart::MainGUIState" o-- "Auctioneer::mainGUI.dart::WidgetMarker"
"Auctioneer::mainGUI.dart::MainGUIState" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"
"Auctioneer::mainGUI.dart::MainGUIState" o-- "Auctioneer::Handlers::filterHandler.dart::FilterHandler"
"Auctioneer::mainGUI.dart::MainGUIState" o-- "Auctioneer::Handlers::auctionHandler.dart::AuctionHandler"
"Auctioneer::mainGUI.dart::MainGUIState" o-- "Auctioneer::Handlers::offerHandler.dart::OfferHandler"



class "Auctioneer::Navigation::navbar.dart::NavigationState" {
  +Function navigate
  +Function showContractTemplateGUI
  +Function showNotifications
  +UserInfoHandler userHandler
  +int counter
  +Widget build()
  +Widget getNotificationsWidgetCounter()
}

"Auctioneer::Navigation::navbar.dart::NavigationState" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"


class "Auctioneer::Pages::login.dart::Login" {
  +Function navigate
  +UserInfoHandler userHandler
  -TextEditingController _controllerUserName
  -TextEditingController _controllerPW
  +dynamic loginUserName
  +dynamic loginPW
  +Widget build()
}

"Auctioneer::Pages::login.dart::Login" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"

class "Auctioneer::Pages::profile.dart::Profile" {
  +Function navigate
  +UserInfoHandler userHandler
  -GlobalKey<FormState> _formKey
  -TextEditingController _controllerUserName
  -TextEditingController _controllerEmail
  -TextEditingController _controllerAge
  -TextEditingController _controllerAddress
  -TextEditingController _controllerCity
  -TextEditingController _controllerState
  -TextEditingController _controllerPostalCode
  -TextEditingController _controllerHomePhoneNumber
  -TextEditingController _controllerMobilePhoneNumber
  -TextEditingController _controllerOfficePhoneNumber
  -TextEditingController _controllerCompany
  -TextEditingController _controllerOPW
  -TextEditingController _controllerPW
  -TextEditingController _controllerRPW
  +dynamic newUserName
  +dynamic newEmail
  +int newAge
  +dynamic newAddress
  +dynamic newCity
  +dynamic newState
  +dynamic newPostalCode
  +dynamic newHomePhoneNumber
  +dynamic newMobilePhoneNumber
  +dynamic newOfficePhoneNumber
  +dynamic newCurrentType
  +dynamic newCompany
  +dynamic opw
  +dynamic pw
  +dynamic rpw
  +Widget build()
}

"Auctioneer::Pages::profile.dart::Profile" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"

class "Auctioneer::Pages::register.dart::Register" {
  +Function navigate
  +UserInfoHandler userHandler
  -TextEditingController _controllerUserName
  -TextEditingController _controllerEmail
  -TextEditingController _controllerPW
  -TextEditingController _controllerRPW
  +dynamic newUserName
  +dynamic newEmail
  +dynamic pw
  +dynamic rpw
  +Widget build()
}

"Auctioneer::Pages::register.dart::Register" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"

class "Auctioneer::Pages::room.dart::_RoomState" {
  +Function navigate
  +AuctionHandler auctionHandler
  +UserInfoHandler userHandler
  +CountdownTimerController controller
  +List<Inbox> out
  +Template contractTemplate
  +List<TextEditingController> controllers
  +MaterialAuction materialAuction
  +Referencetype2Auction referencetype2Auction
  +bool isFinished
  +bool isHost
  +TextStyle smallText
  +TextStyle bigText
  +TextStyle boldText
  +Widget build()
  +bool checkForNotifications()
  +void showContractGUI()
}

"Auctioneer::Pages::room.dart::_RoomState" o-- "Auctioneer::Handlers::auctionHandler.dart::AuctionHandler"
"Auctioneer::Pages::room.dart::_RoomState" o-- "Auctioneer::Handlers::userInfoHandler.dart::UserInfoHandler"
"Auctioneer::Pages::room.dart::_RoomState" o-- "Auctioneer::Entities::templateListJSON.dart::Template"
"Auctioneer::Pages::room.dart::_RoomState" o-- "Auctioneer::Entities::materialAuctionListJSON.dart::MaterialAuction"
"Auctioneer::Pages::room.dart::_RoomState" o-- "Auctioneer::Entities::referencetype2AuctionListJSON.dart::Referencetype2Auction"


@enduml